[package]
name = "RSRemakeTutorLoL"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.129"
tokio = { version = "1.40.0", features = ["full"] }
