//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "account")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub account_id: String,
    pub email: String,
    pub created_at: DateTime,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::account_summoner::Entity")]
    AccountSummoner,
}

impl Related<super::account_summoner::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountSummoner.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
