//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "games")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub game_id: String,
    pub summoner_name: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub game_code: Option<String>,
    pub champion_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::game_data::Entity")]
    GameData,
}

impl Related<super::game_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
