//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::account::Entity as Account;
pub use super::account_summoner::Entity as AccountSummoner;
pub use super::game_data::Entity as GameData;
pub use super::games::Entity as Games;
pub use super::log::Entity as Log;
